<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pe.edu.galaxy.framework</groupId>
        <artifactId>galaxy-custom-framework-parent</artifactId>
        <version>1.0.5</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>framework-bom</artifactId>
    <packaging>pom</packaging>
    <name>Galaxy Framework BOM</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-cqrs-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-bus-spring</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-jpa-exception-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-architecture-hexagonal</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-openapi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-id-fraud</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-spring-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-test-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
