<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <groupId>pe.edu.galaxy.app</groupId>
    <artifactId>poc-integracion</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>POC Integración</name>

    <properties>
        <java.version>21</java.version>
        <framework.version>1.0.5</framework.version>
        <galaxy.starters.version>3.0.3</galaxy.starters.version>
        <openapi-generator.version>7.11.0</openapi-generator.version>
        <archunit.version>1.4.1</archunit.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>pe.edu.galaxy.framework</groupId>
                <artifactId>framework-bom</artifactId>
                <version>${framework.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>pe.edu.galaxy.training.java.bom</groupId>
                <artifactId>oms-starter-bom-core</artifactId>
                <version>${galaxy.starters.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <repositories>
        <repository>
            <id>nexus-releases</id>
            <url>http://localhost:8089/repository/maven-releases/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>nexus-snapshots</id>
            <url>http://localhost:8089/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>pe.edu.galaxy.framework</groupId>
            <artifactId>framework-architecture-hexagonal</artifactId>
        </dependency>
        <dependency>
            <groupId>pe.edu.galaxy.framework</groupId>
            <artifactId>framework-jpa-exception-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pe.edu.galaxy.framework</groupId>
            <artifactId>framework-bus-spring</artifactId>
        </dependency>
        <dependency>
            <groupId>pe.edu.galaxy.framework</groupId>
            <artifactId>framework-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>pe.edu.galaxy.framework</groupId>
            <artifactId>framework-id-fraud</artifactId>
        </dependency>
        <dependency>
            <groupId>pe.edu.galaxy.framework</groupId>
            <artifactId>framework-spring-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>pe.edu.galaxy.framework</groupId>
            <artifactId>framework-test-starter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit</artifactId>
            <version>${archunit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator.version}</version>
                <executions>
                    <execution>
                        <id>generate-creditcard-server</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/openapi/openapi-creditcard.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <apiPackage>pe.edu.galaxy.pocintegracion.generated.server.api</apiPackage>
                            <modelPackage>pe.edu.galaxy.pocintegracion.generated.server.model</modelPackage>
                            <invokerPackage>pe.edu.galaxy.pocintegracion.generated.server</invokerPackage>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <configOptions>
                                <interfaceOnly>false</interfaceOnly>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <useSpringBoot3>true</useSpringBoot3>
                                <openApiNullable>false</openApiNullable>
                                <documentationProvider>none</documentationProvider>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>pe.edu.galaxy.pocintegracion.PocIntegracionApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>with-galaxy-starters</id>
            <activation>
                <property>
                    <name>withGalaxyStarters</name>
                    <value>true</value>
                </property>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>pe.edu.galaxy.training.java</groupId>
                    <artifactId>oms-starter-logs-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>pe.edu.galaxy.training.java</groupId>
                    <artifactId>oms-starter-audit-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>pe.edu.galaxy.training.java</groupId>
                    <artifactId>oms-starter-security-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>pe.edu.galaxy.training.java</groupId>
                    <artifactId>oms-starter-observability-core</artifactId>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
